#!/bin/bash
set -e

echo '----------'
echo 'go version'
docker-compose run --rm hugo go version

echo '--------------'
echo 'hugo version'
docker-compose run --rm hugo hugo version

echo '-------------------'
echo 'cat /etc/os-release'
docker-compose run --rm hugo cat /etc/os-release

echo '---'
echo 'env'
docker-compose run --rm hugo env
