version: "3"

services:
  hugo:
    build: .
    ports:
      - 1313:1313
    volumes:
      - .:/home/winner/neutrino
    working_dir: /home/winner/neutrino
    user: winner
    command:
      - hugo
      - server
      - -D
      - --bind=0.0.0.0
